[project]
name = "container-dead-monitor"
version = "0.1.0"
description = "A simple container monitor to send discord webhook alerts"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docker>=7.1.0",
    "requests>=2.32.3",
]
